# Generated by Django 5.1.1 on 2024-09-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="popularity",
            field=models.IntegerField(default=0),
        ),
    ]
