# Generated by Django 4.2.6 on 2023-10-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.istockphoto.com/photo/person-getting-a-piece-of-cheesy-pepperoni-pizza-gm1442417585-481780510', max_length=500),
        ),
    ]
