# Generated by Django 4.2.6 on 2023-10-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://media.istockphoto.com/id/676621982/photo/cutting-pizza-on-slices.jpg?s=612x612&w=is&k=20&c=AjkjjNImS_abqThxMCfoCYNh8nMw-LH7OQLBKCDAbUw=', max_length=500),
        ),
    ]
