# Generated by Django 5.1.1 on 2024-09-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0003_alter_item_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://media.istockphoto.com/id/676621982/photo/cutting-pizza-on-slices.jpg?s=612x612&w=is&k=20&c=AjkjjNImS_abqThxMCfoCYNh8nMw-LH7OQLBKCDAbUw=",
                max_length=200,
            ),
        ),
    ]
