name: multi_db_ecommerce CI/CD

on:
  push:
    paths:
      - 'multi_db_ecommerce/**'
  pull_request:
    paths:
      - 'multi_db_ecommerce/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        cd multi_db_ecommerce
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd multi_db_ecommerce
        python manage.py test
