# Generated by Django 4.1.13 on 2024-10-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Products", "0002_product_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("product_id", models.CharField(max_length=255)),
                ("review_content", models.TextField()),
                ("rating", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
